"""remove isbn from books

Revision ID: 9fffc6263543
Revises: 69cbbb624901
Create Date: 2025-09-10 23:07:50.226625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fffc6263543'
down_revision: Union[str, Sequence[str], None] = '69cbbb624901'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('books_isbn_key'), 'books', type_='unique')
    op.drop_column('books', 'isbn')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('isbn', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('books_isbn_key'), 'books', ['isbn'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
