""" added foreign key to the book table

Revision ID: af4203e383ff
Revises: 1516a5d1b12c
Create Date: 2025-09-14 20:00:46.047131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af4203e383ff'
down_revision: Union[str, Sequence[str], None] = '1516a5d1b12c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('created_by', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'books', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_column('books', 'created_by')
    # ### end Alembic commands ###
