""" added foreign key to the book table

Revision ID: baedbb9d737f
Revises: a3ce4bcca2ba
Create Date: 2025-09-15 23:02:20.849429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'baedbb9d737f'
down_revision: Union[str, Sequence[str], None] = 'a3ce4bcca2ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_id_key'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('users_id_key'), 'users', ['id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
